version: "3"

volumes:
  sqlvolume:

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      - MSSQL_SA_PASSWORD=Abcd@1234
      - ACCEPT_EULA=Y
    container_name: sql-server
    volumes:
      - sqlvolume:/var/opt/mssql
    ports:
      - 1433:1433
